from django.urls import path
from .views import (
    BusinessListView, BusinessDetailView, MyBusinessListView, AdminBusinessListView, AdminBusinessDetailView,
    BusinessEmployeeListCreateView, BusinessEmployeeDetailView, AdminModerationListView, AdminModerationDeskView,
    AdminModerationApproveView, AdminModerationRejectView, AdminCSVImportView, PublicBusinessRegistrationView,
    BusinessRoleListCreateView, BusinessRoleDetailView, SeedReceptionistRoleView,
    MyBusinessSubscriptionView, MyBusinessAuditLogsView, AdminBusinessSubscriptionView, AdminSubscriptionListView,
    MySubscriptionBurundiPayPayView, MySubscriptionBurundiPayConfirmView, BurundiPaySubscriptionWebhookView,
    AdminSubscriptionPaymentListView, AdminPlatformNotificationListView,
    AdminSubscriptionPlansView, AdminSubscriptionPlanDetailView, AdminSubscriptionSettingsView,
)

urlpatterns = [
    path('register/', PublicBusinessRegistrationView.as_view(), name='business-register-public'),
    path('', BusinessListView.as_view(), name='business-list-public'),
    path('<uuid:pk>/', BusinessDetailView.as_view(), name='business-detail-public'),
    path('me/', MyBusinessListView.as_view(), name='my-business-list-create'),
    path('me/subscription/', MyBusinessSubscriptionView.as_view(), name='my-business-subscription'),
    path('me/audit-logs/', MyBusinessAuditLogsView.as_view(), name='my-business-audit-logs'),
    path('me/subscription/pay/', MySubscriptionBurundiPayPayView.as_view(), name='my-business-subscription-pay'),
    path('me/subscription/confirm/', MySubscriptionBurundiPayConfirmView.as_view(), name='my-business-subscription-confirm'),
    path('payments/burundipay/webhook/', BurundiPaySubscriptionWebhookView.as_view(), name='burundipay-subscription-webhook'),
    # Alias legacy Lumicash
    path('payments/lumicash/webhook/', BurundiPaySubscriptionWebhookView.as_view(), name='lumicash-subscription-webhook'),
    path('my-business/roles/', BusinessRoleListCreateView.as_view(), name='my-business-roles'),
    path('my-business/roles/seed-receptionist/', SeedReceptionistRoleView.as_view(), name='my-business-roles-seed-receptionist'),
    path('my-business/roles/<uuid:pk>/', BusinessRoleDetailView.as_view(), name='my-business-roles-detail'),
    path('my-business/employees/', BusinessEmployeeListCreateView.as_view(), name='my-business-employees'),
    path('my-business/employees/<uuid:pk>/', BusinessEmployeeDetailView.as_view(), name='my-business-employee-detail'),
    path('admin/list/', AdminBusinessListView.as_view(), name='admin_business_list'),
    path('admin/subscriptions/', AdminSubscriptionListView.as_view(), name='admin_subscriptions_list'),
    path('admin/plans/', AdminSubscriptionPlansView.as_view(), name='admin_subscription_plans'),
    path('admin/subscription-settings/', AdminSubscriptionSettingsView.as_view(), name='admin_subscription_settings'),
    path('admin/plans/<slug:code>/', AdminSubscriptionPlanDetailView.as_view(), name='admin_subscription_plan_detail'),
    path('admin/subscription-payments/', AdminSubscriptionPaymentListView.as_view(), name='admin_subscription_payments'),
    path('admin/notifications/', AdminPlatformNotificationListView.as_view(), name='admin_platform_notifications'),
    path('admin/<uuid:pk>/', AdminBusinessDetailView.as_view(), name='admin_business_detail'),
    path('admin/<uuid:pk>/subscription/', AdminBusinessSubscriptionView.as_view(), name='admin_business_subscription'),
    path('admin/moderation/', AdminModerationListView.as_view(), name='admin_moderation_list'),
    path('admin/moderation/desk/', AdminModerationDeskView.as_view(), name='admin_moderation_desk'),
    path('admin/moderation/<uuid:pk>/approve/', AdminModerationApproveView.as_view(), name='admin_moderation_approve'),
    path('admin/moderation/<uuid:pk>/reject/', AdminModerationRejectView.as_view(), name='admin_moderation_reject'),
    path('admin/import-csv/', AdminCSVImportView.as_view(), name='admin_import_csv'),
]
