# Generated by Django 5.2.17 on 2026-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, help_text="URL ou image Base64 de l'avatar"),
        ),
    ]
