# Generated by Django 5.2.17 on 2026-09-03 08:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column', models.CharField(choices=[('COMPANY', 'Company'), ('SUPPORT', 'Support'), ('LEGAL', 'Legal'), ('OTHER', 'Other')], default='COMPANY', max_length=20)),
                ('column_title', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=500)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['column', 'display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='Isoko Hub', max_length=120)),
                ('footer_tagline', models.TextField(default='Everything you need, in one platform. Connecting Burundi to the world.')),
                ('footer_copyright', models.CharField(blank=True, default='© Isoko Hub. All rights reserved.', max_length=255)),
                ('hero_title', models.TextField(default='Everything you need,\nin one platform.')),
                ('hero_subtitle', models.TextField(default='Find trusted professionals, book services, order from the best businesses, and discover new opportunities in Burundi.')),
                ('hero_cta_primary_label', models.CharField(default='Créer une Entreprise', max_length=120)),
                ('hero_cta_primary_url', models.CharField(default='/register-business', max_length=255)),
                ('hero_cta_secondary_label', models.CharField(default='Explore Services', max_length=120)),
                ('hero_cta_secondary_url', models.CharField(default='/services', max_length=255)),
                ('search_placeholder', models.CharField(default='Profession, Business, Restaurant, Product...', max_length=255)),
                ('search_location_placeholder', models.CharField(default='Location', max_length=120)),
                ('categories_title', models.CharField(default='Explore Categories', max_length=150)),
                ('professionals_title', models.CharField(default='Featured Professionals', max_length=150)),
                ('health_title', models.CharField(default='Établissements de Santé', max_length=150)),
                ('businesses_title', models.CharField(default='Top Businesses', max_length=150)),
                ('services_title', models.CharField(default='Popular Services', max_length=150)),
                ('why_title', models.CharField(default='Why choose Isoko Hub?', max_length=150)),
                ('why_items', models.JSONField(blank=True, default=list)),
                ('app_banner_title', models.CharField(default='Take Isoko Hub everywhere', max_length=200)),
                ('app_banner_subtitle', models.TextField(default='The official Isoko Hub mobile app is currently under development.')),
                ('app_banner_badge', models.CharField(default='COMING SOON', max_length=80)),
                ('show_categories', models.BooleanField(default=True)),
                ('show_professionals', models.BooleanField(default=True)),
                ('show_health', models.BooleanField(default=True)),
                ('show_businesses', models.BooleanField(default=True)),
                ('show_services', models.BooleanField(default=True)),
                ('show_why', models.BooleanField(default=True)),
                ('show_app_banner', models.BooleanField(default=True)),
                ('show_partners', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
