# Generated by Django 5.2.17 on 2026-09-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='platform_logo',
            field=models.TextField(blank=True, help_text='URL ou image Base64 du logo plateforme (header/footer)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_page_subtitle',
            field=models.CharField(default='Discover trusted professionals for any job', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_page_title',
            field=models.CharField(default='Find Services', max_length=150),
        ),
    ]
