# Generated by Django 5.2.17 on 2026-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='support@isokohub.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact information', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_follow_title',
            field=models.CharField(blank=True, default='Follow us', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_headline',
            field=models.CharField(blank=True, default='Tout ce dont vous avez besoin — en une seule plateforme.', help_text='Grand titre en haut du footer', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_button',
            field=models.CharField(blank=True, default="S'abonner", max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_placeholder',
            field=models.CharField(blank=True, default='Votre email', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_title',
            field=models.CharField(blank=True, default='Restez informé !', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_show_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
