# Generated by Django 5.2.17 on 2026-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_footer_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_subtitle',
            field=models.CharField(blank=True, default='Isoko Hub est prêt à vous accompagner selon vos besoins.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro',
            field=models.TextField(blank=True, default='Une question sur la plateforme, un partenariat ou un besoin support ? Écrivez-nous — l’équipe Super Admin vous répondra.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_map_lat',
            field=models.CharField(blank=True, default='-3.3731', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_map_lng',
            field=models.CharField(blank=True, default='29.9189', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_office_address',
            field=models.CharField(blank=True, default='Bujumbura, Burundi', max_length=255),
        ),
    ]
