# Generated by Django 5.2.17 on 2026-09-03 09:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0014_alter_businessrole_system_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_carts', to='businesses.business')),
                ('wholesale_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_carts_as_supplier', to='businesses.business')),
            ],
            options={
                'unique_together': {('client_business', 'wholesale_business')},
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Envoyee'), ('PROCESSING', 'En cours de traitement'), ('ACCEPTED', 'Acceptee'), ('REJECTED', 'Refusee'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('refusal_reason', models.CharField(blank=True, max_length=255)),
                ('refusal_comment', models.TextField(blank=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('refused_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_orders_accepted', to=settings.AUTH_USER_MODEL)),
                ('client_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_orders_placed', to='businesses.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_orders_created', to=settings.AUTH_USER_MODEL)),
                ('refused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_orders_refused', to=settings.AUTH_USER_MODEL)),
                ('wholesale_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_orders_received', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(default='ORDER_ACCEPTED', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoye'), ('FAILED', 'Echec')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='wholesale.wholesaleorder')),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleOrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wholesale.wholesaleorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesalePharmacyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commercial_name', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('CLOSED', 'Fermee')], default='ACTIVE', max_length=20)),
                ('order_reference_prefix', models.CharField(default='CMD-PG', max_length=20)),
                ('acceptance_email_message', models.TextField(blank=True, default='Bonjour,\n\nVotre commande {reference} a ete acceptee par {wholesale_name}.\nMontant total : {total_amount} {currency}.\n\nMerci de nous contacter pour la suite de la collaboration.\n\nCordialement,\n{wholesale_name}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_profile', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active_ingredient', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('pharmaceutical_form', models.CharField(blank=True, max_length=120)),
                ('administration_route', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('packaging', models.CharField(help_text='Ex: Boite de 20 comprimes', max_length=255)),
                ('wholesale_unit', models.CharField(default='Boite', max_length=120)),
                ('min_order_quantity', models.PositiveIntegerField(default=1)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('quantity_real', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('batch_number', models.CharField(blank=True, max_length=120)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('ARCHIVED', 'Archive')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wholesale_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_products', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('packaging_snapshot', models.CharField(max_length=255)),
                ('wholesale_unit_snapshot', models.CharField(blank=True, max_length=120)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesale.wholesaleorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='wholesale.wholesaleproduct')),
            ],
            options={
                'ordering': ['product_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='wholesale.wholesaleorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='wholesale.wholesaleproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesale.wholesalecart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.wholesaleproduct')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
