# Generated by Django 5.2.17 on 2026-09-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_alter_businessrole_system_access_level'),
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleorder',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='buyer_type',
            field=models.CharField(choices=[('PERSON', 'Personne'), ('RETAIL_PHARMACY', 'Pharmacie de detail')], default='PERSON', max_length=30),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL image du medicament'),
        ),
        migrations.AlterField(
            model_name='wholesaleorder',
            name='client_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_orders_placed', to='businesses.business'),
        ),
    ]
