# Generated by Django 5.2.17 on 2026-09-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_product_image_and_guest_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleproduct',
            name='therapeutic_class',
            field=models.CharField(blank=True, help_text='Ex: Antidouleur, Antibiotique', max_length=120),
        ),
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='image_url',
            field=models.TextField(blank=True, help_text='Image du medicament (URL ou data URI)'),
        ),
    ]
