# Generated by Django 5.2.16 on 2026-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.CharField(blank=True, help_text='URL du logo', max_length=255),
        ),
    ]
