# Generated by Django 5.2.17 on 2026-08-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_categories', '0002_businesscategory_parent'),
        ('businesses', '0003_alter_business_options_businessemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='business_categories.businesscategory'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_businesses', to='business_categories.businesscategory'),
        ),
    ]
