# Generated by Django 5.2.17 on 2026-08-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_categories', '0002_businesscategory_parent'),
        ('businesses', '0004_business_categories_alter_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_businesses', to='business_categories.businesscategory'),
        ),
    ]
