# Generated by Django 5.2.17 on 2026-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_primary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Spécificités métiers par secteur (ex: agrément, étoiles, piscine, cuisine...)'),
        ),
    ]
