# Generated by Django 5.2.17 on 2026-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_extra_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='proof_document',
            field=models.CharField(blank=True, help_text='URL du justificatif / Agrément ministériel', max_length=555),
        ),
        migrations.AddField(
            model_name='business',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motif du rejet par la modération'),
        ),
        migrations.AddField(
            model_name='business',
            name='verification_status',
            field=models.CharField(choices=[('APPROVED', 'Approuvé'), ('PENDING', 'En attente de validation'), ('REJECTED', 'Rejeté')], default='APPROVED', max_length=20),
        ),
    ]
