# Generated by Django 5.2.17 on 2026-08-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_proof_document_business_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='commune',
            field=models.CharField(blank=True, help_text='Commune (ex: Mukaza, Ntahangwa, Muha...)', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS Latitude', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS Longitude', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='province',
            field=models.CharField(default='Bujumbura Mairie', help_text='Province du siège', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='quartier',
            field=models.CharField(blank=True, help_text='Quartier/Zone (ex: Rohero, Bwiza, Ngagara...)', max_length=100),
        ),
    ]
