# Generated by Django 5.2.17 on 2026-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_business_commune_business_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='avenue',
            field=models.CharField(blank=True, help_text='Avenue/Rue (Optionnel)', max_length=150),
        ),
        migrations.AddField(
            model_name='business',
            name='zone',
            field=models.CharField(blank=True, help_text='Zone administrative', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='quartier',
            field=models.CharField(blank=True, help_text='Quartier/Colline (ex: Rohero I, Bwiza, Ngagara...)', max_length=100),
        ),
    ]
