# Generated by Django 5.2.17 on 2026-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_business_avenue_business_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.TextField(blank=True, help_text='URL ou Image Base64 du logo'),
        ),
    ]
