# Generated by Django 5.2.17 on 2026-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_alter_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
