# Generated by Django 5.2.17 on 2026-08-18 13:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_alter_business_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemployee',
            name='position',
            field=models.CharField(blank=True, default='Staff', max_length=100),
        ),
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom personnalisé du rôle (ex: Infirmier de Nuit)', max_length=150)),
                ('system_access_level', models.CharField(choices=[('ADMIN_ACCESS', 'Accès Administrateur'), ('MEDICAL_ACCESS', 'Accès Médical (Médecins, Spécialistes)'), ('LAB_ACCESS', 'Accès Laboratoire'), ('CASHIER_ACCESS', 'Accès Caisse & Facturation'), ('STAFF_ACCESS', 'Accès Staff Standard')], default='STAFF_ACCESS', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='businessemployee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='businesses.businessrole'),
        ),
    ]
