# Generated by Django 5.2.17 on 2026-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_alter_businessemployee_position_businessrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrole',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Liste des clés de permissions accordées au rôle'),
        ),
    ]
