# Generated by Django 5.2.17 on 2026-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_businessrole_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrole',
            name='system_access_level',
            field=models.CharField(choices=[('ADMIN_ACCESS', 'Accès Administrateur'), ('MEDICAL_ACCESS', 'Accès Médical (Médecins, Spécialistes)'), ('RECEPTIONIST_ACCESS', 'Accès Accueil & Réception'), ('LAB_ACCESS', 'Accès Laboratoire'), ('CASHIER_ACCESS', 'Accès Caisse & Facturation'), ('STAFF_ACCESS', 'Accès Staff Standard')], default='STAFF_ACCESS', max_length=50),
        ),
    ]
