# Generated by Django 5.2.17 on 2026-09-11 07:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_business_lumicash_merchant_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Free'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('SUSPENDED', 'Suspendu'), ('CANCELLED', 'Annulé')], default='TRIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='CommerceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commercial_name', models.CharField(blank=True, default='', max_length=255)),
                ('order_reference_prefix', models.CharField(default='CMD', max_length=20)),
                ('pickup_instructions', models.TextField(blank=True, default='Retrait en magasin après confirmation de paiement.')),
                ('is_open_for_orders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_profile', to='businesses.business')),
            ],
        ),
    ]
