# Generated by Django 5.2.17 on 2026-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_commerce_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerceprofile',
            name='nif_document',
            field=models.TextField(blank=True, default='', help_text='Scan NIF (data URL)'),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='nif_document_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='nif_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text="NIF — Numéro d'Identification Fiscale (OBR)", max_length=64),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='permit_document',
            field=models.TextField(blank=True, default='', help_text='Scan patente / autorisation'),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='permit_document_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='permit_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Patente / autorisation d'exercer / attestation communale", max_length=64),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='rccm_document',
            field=models.TextField(blank=True, default='', help_text='Scan RCCM (data URL)'),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='rccm_document_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='commerceprofile',
            name='rccm_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='RCCM — Registre du Commerce et du Crédit Mobilier', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='commerceprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('nif_number', ''), _negated=True), fields=('nif_number',), name='uniq_commerce_nif_number'),
        ),
        migrations.AddConstraint(
            model_name='commerceprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('rccm_number', ''), _negated=True), fields=('rccm_number',), name='uniq_commerce_rccm_number'),
        ),
        migrations.AddConstraint(
            model_name='commerceprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('permit_number', ''), _negated=True), fields=('permit_number',), name='uniq_commerce_permit_number'),
        ),
        migrations.AddConstraint(
            model_name='commerceprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('nif_document_hash', ''), _negated=True), fields=('nif_document_hash',), name='uniq_commerce_nif_doc_hash'),
        ),
        migrations.AddConstraint(
            model_name='commerceprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('rccm_document_hash', ''), _negated=True), fields=('rccm_document_hash',), name='uniq_commerce_rccm_doc_hash'),
        ),
        migrations.AddConstraint(
            model_name='commerceprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('permit_document_hash', ''), _negated=True), fields=('permit_document_hash',), name='uniq_commerce_permit_doc_hash'),
        ),
    ]
