# Generated by Django 5.2.16 on 2026-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CUSTOMER', 'Customer'), ('PROFESSIONAL', 'Professional'), ('BUSINESS_OWNER', 'Business Owner')], default='CUSTOMER', max_length=50),
        ),
    ]
