# Generated by Django 5.2.17 on 2026-09-10 15:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('github', 'GitHub')], db_index=True, max_length=20)),
                ('provider_user_id', models.CharField(db_index=True, max_length=191)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identité sociale',
                'verbose_name_plural': 'Identités sociales',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uniq_social_provider_uid')],
            },
        ),
    ]
