"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-@va@2#7tz!m!b=0bedv^slp$a&$!ho1)4l@v6nspuzlc(djtou')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == '1'

_allowed = os.environ.get('ALLOWED_HOSTS', '*').strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] or ['*']

# Origines CORS (prod : liste explicite ; DEBUG : ouvert)
_cors = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
if _cors:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors.split(',') if o.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG or os.environ.get('CORS_ALLOW_ALL', '1') == '1'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'roles',
    'permissions',
    'business_categories',
    'businesses.apps.BusinessesConfig',
    'profiles',
    'service_categories',
    'services',
    'product_categories',
    'products',
    'offers',
    'analytics',
    'locations',
    'hospital',
    'hotel.apps.HotelConfig',
    'wholesale',
    'retail',
    'bookings',
    'orders',
    'site_content',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'businesses.middleware.ActiveSubscriptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS défini plus haut selon l'environnement

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'isoko_hub_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# SQLite pour les tests unitaires (sans PostgreSQL)
import sys
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'accounts.password_validation.ConfigurableMinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Uploads (ordonnances retail, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Ordonnance max ~8 Mo (images / PDF)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 8 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173').strip().strip('"')
BACKEND_URL = os.environ.get('BACKEND_URL', 'http://localhost:8000').strip().strip('"')

# --- OAuth social (Google / Facebook / GitHub) ---
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '').strip()
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '').strip()
FACEBOOK_OAUTH_CLIENT_ID = os.environ.get('FACEBOOK_OAUTH_CLIENT_ID', '').strip()
FACEBOOK_OAUTH_CLIENT_SECRET = os.environ.get('FACEBOOK_OAUTH_CLIENT_SECRET', '').strip()
GITHUB_OAUTH_CLIENT_ID = os.environ.get('GITHUB_OAUTH_CLIENT_ID', '').strip()
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', '').strip()

# Email — SMTP si EMAIL_HOST est défini, sinon console (logs Docker)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip().strip('"')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') in ('1', 'true', 'True', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '0') in ('1', 'true', 'True', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip().strip('"')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').strip().strip('"')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@isokohub.bi').strip().strip('"')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '30'))

if EMAIL_HOST:
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND',
        'django.core.mail.backends.smtp.EmailBackend',
    )
else:
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND',
        'django.core.mail.backends.console.EmailBackend',
    )

AUTH_USER_MODEL = 'accounts.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Limitation de débit — protège l'API à grande échelle
    # Soft* : pas de throttle en DEBUG (SPA locale multiplie les GET).
    'DEFAULT_THROTTLE_CLASSES': [
        'config.throttling.SoftAnonRateThrottle',
        'config.throttling.SoftUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_ANON', '120/min'),
        'user': os.environ.get('THROTTLE_USER', '600/min'),
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# --- Sécurité SaaS (chiffrement en transit / cookies / headers) ---
# Activé automatiquement hors DEBUG. Forcer avec SECURE_SSL=1 même en DEBUG.
_secure = (not DEBUG) or os.environ.get('SECURE_SSL', '0') in ('1', 'true', 'True')
SECURE_SSL_REDIRECT = _secure and os.environ.get('SECURE_SSL_REDIRECT', '1') in ('1', 'true', 'True')
SESSION_COOKIE_SECURE = _secure
CSRF_COOKIE_SECURE = _secure
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
if _secure:
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Répertoire des sauvegardes opérationnelles (hors volume DB)
BACKUP_ROOT = Path(os.environ.get('BACKUP_ROOT', str(BASE_DIR / 'backups')))
BACKUP_RETENTION_DAYS = int(os.environ.get('BACKUP_RETENTION_DAYS', '14'))

# --- BurundiPay (paiements instantanés banques + mobile money) ---
# Compat : LUMICASH_* encore accepté en fallback pendant la transition.
def _env_first(*keys, default=''):
    for key in keys:
        val = os.environ.get(key)
        if val is not None and str(val).strip() != '':
            return str(val).strip()
    return default

BURUNDIPAY_STUB = _env_first('BURUNDIPAY_STUB', 'LUMICASH_STUB', default='1') in ('1', 'true', 'True', 'yes')
BURUNDIPAY_MERCHANT_ACCOUNT = _env_first(
    'BURUNDIPAY_MERCHANT_ACCOUNT', 'LUMICASH_MERCHANT_ACCOUNT', default='ISOKO_HUB_MERCHANT'
)
BURUNDIPAY_API_URL = _env_first('BURUNDIPAY_API_URL', 'LUMICASH_API_URL', default='')
BURUNDIPAY_API_KEY = _env_first('BURUNDIPAY_API_KEY', 'LUMICASH_API_KEY', default='')
BURUNDIPAY_WEBHOOK_SECRET = _env_first('BURUNDIPAY_WEBHOOK_SECRET', 'LUMICASH_WEBHOOK_SECRET', default='')
BURUNDIPAY_CALLBACK_URL = _env_first('BURUNDIPAY_CALLBACK_URL', 'LUMICASH_CALLBACK_URL', default='')
BURUNDIPAY_COLLECT_PATH = _env_first('BURUNDIPAY_COLLECT_PATH', default='/v1/collections')
BURUNDIPAY_STATUS_PATH = _env_first('BURUNDIPAY_STATUS_PATH', default='/v1/collections/{id}')
BURUNDIPAY_REFUND_PATH = _env_first('BURUNDIPAY_REFUND_PATH', default='/v1/refunds')
BURUNDIPAY_HTTP_TIMEOUT = _env_first('BURUNDIPAY_HTTP_TIMEOUT', default='30')
# Alias historiques pour code / imports legacy
LUMICASH_STUB = BURUNDIPAY_STUB
LUMICASH_MERCHANT_ACCOUNT = BURUNDIPAY_MERCHANT_ACCOUNT
LUMICASH_API_URL = BURUNDIPAY_API_URL
LUMICASH_API_KEY = BURUNDIPAY_API_KEY
LUMICASH_WEBHOOK_SECRET = BURUNDIPAY_WEBHOOK_SECRET
LUMICASH_CALLBACK_URL = BURUNDIPAY_CALLBACK_URL
# Prod : stub interdit sauf override explicite
if (not DEBUG) and BURUNDIPAY_STUB and _env_first(
    'BURUNDIPAY_ALLOW_STUB_IN_PROD', 'LUMICASH_ALLOW_STUB_IN_PROD', default='0'
) not in ('1', 'true', 'True', 'yes'):
    raise ImproperlyConfigured(
        'BURUNDIPAY_STUB=1 est interdit hors DEBUG. '
        'Configurez BURUNDIPAY_API_URL/KEY et BURUNDIPAY_STUB=0, '
        'ou forcez BURUNDIPAY_ALLOW_STUB_IN_PROD=1 uniquement pour un staging contrôlé.'
    )

# Allow large payloads (e.g. Base64 images)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
