# Generated by Django 5.2.17 on 2026-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_guest_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='classification_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='customer_service_hours',
            field=models.CharField(blank=True, default='', help_text='Ex. Lun–Dim 07:00–22:00', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='deposit_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='establishment_type',
            field=models.CharField(choices=[('HOTEL', 'Hôtel'), ('GUEST_HOUSE', 'Guest house'), ('LODGE', 'Lodge'), ('RESIDENCE', 'Résidence'), ('HOSTEL', 'Auberge'), ('OTHER', 'Autre hébergement')], default='HOTEL', max_length=30),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Ex. ["fr","en","rn"]'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='stars_verified',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Étoiles vérifiées par la plateforme', null=True),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='stay_conditions',
            field=models.TextField(blank=True, default='', help_text="Règles propres à l'établissement (visiteurs, âge, documents…)"),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='includes_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='min_nights',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='rate_kind',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('WEEKEND', 'Week-end'), ('HIGH_SEASON', 'Haute saison'), ('LOW_SEASON', 'Basse saison'), ('LONG_STAY', 'Longue durée'), ('GROUP', 'Groupe'), ('CORPORATE', 'Entreprise'), ('BREAKFAST', 'Petit-déjeuner inclus')], default='STANDARD', max_length=30),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='taxes_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='surface_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='hotelprofile',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Étoiles déclarées', null=True),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='currency',
            field=models.CharField(choices=[('BIF', 'BIF'), ('USD', 'USD'), ('EUR', 'EUR')], default='BIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='operational_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Occupée'), ('RESERVED', 'Réservée'), ('CLEANING', 'Nettoyage'), ('OUT_OF_SERVICE', 'Hors service'), ('MAINTENANCE', 'En maintenance'), ('BLOCKED', 'Bloquée')], default='AVAILABLE', max_length=30),
        ),
    ]
