# Generated by Django 5.2.17 on 2026-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotellerie2_profile_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='currency',
            field=models.CharField(default='BIF', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payer_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_merchant_account',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_provider_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Non payé'), ('AWAITING_PIN', 'En attente validation PIN'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('WAIVED', 'Exonéré'), ('REFUNDED', 'Remboursé')], db_index=True, default='UNPAID', max_length=20),
        ),
    ]
