# Generated by Django 5.2.17 on 2026-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_cashclosing_breakdown_payment_burundipay'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Libellé affiché côté client (ex. confort, luxe, suite)', max_length=80),
        ),
    ]
