# Generated by Django 5.2.17 on 2026-09-04 10:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0014_alter_businessrole_system_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_carts', to=settings.AUTH_USER_MODEL)),
                ('retail_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_carts_as_supplier', to='businesses.business')),
            ],
            options={
                'unique_together': {('patient', 'retail_business')},
            },
        ),
        migrations.CreateModel(
            name='RetailOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(blank=True, max_length=40)),
                ('is_guest', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Envoyee'), ('PROCESSING', 'En cours de traitement'), ('CLARIFICATION_REQUESTED', 'Clarification demandee'), ('ACCEPTED', 'Acceptee'), ('REJECTED', 'Refusee'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('rejection_comment', models.TextField(blank=True)),
                ('clarification_comment', models.TextField(blank=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_orders_accepted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_orders_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_orders', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_orders_rejected', to=settings.AUTH_USER_MODEL)),
                ('retail_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_orders_received', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_VALIDATION', 'En attente de validation'), ('CONFIRMED', 'Confirmee'), ('CANCELLED', 'Annulee'), ('REJECTED', 'Refusee')], default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('lines_snapshot', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_proformas', to=settings.AUTH_USER_MODEL)),
                ('retail_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_proformas_issued', to='businesses.business')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='retail.retailcart')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma', to='retail.retailorder')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('file_url', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWED', 'Examinee'), ('ACCEPTED', 'Acceptee'), ('REJECTED', 'Refusee')], default='PENDING', max_length=20)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('retail_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_prescriptions', to='businesses.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_prescriptions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='retail.retailorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(default='ORDER_ACCEPTED', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoye'), ('FAILED', 'Echec')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='retail.retailorder')),
            ],
        ),
        migrations.CreateModel(
            name='RetailOrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='retail.retailorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_order_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailPharmacyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commercial_name', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('CLOSED', 'Fermee')], default='ACTIVE', max_length=20)),
                ('order_reference_prefix', models.CharField(default='CMD-PD', max_length=20)),
                ('acceptance_email_message', models.TextField(blank=True, default='Bonjour {patient_name},\n\nVotre commande {reference} a ete acceptee par {pharmacy_name}.\nMontant total : {total_amount} {currency}.\n\nCordialement,\n{pharmacy_name}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retail_profile', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='RetailProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active_ingredient', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('pharmaceutical_form', models.CharField(blank=True, max_length=120)),
                ('administration_route', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('packaging', models.CharField(max_length=255)),
                ('sales_unit', models.CharField(default='Boite', max_length=120)),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('prescription_required', models.BooleanField(default=False)),
                ('quantity_real', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('batch_number', models.CharField(blank=True, max_length=120)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('ARCHIVED', 'Archive')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('therapeutic_class', models.CharField(blank=True, max_length=120)),
                ('image_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retail_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_products', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetailOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('packaging_snapshot', models.CharField(max_length=255)),
                ('sales_unit_snapshot', models.CharField(blank=True, max_length=120)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prescription_required_snapshot', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail.retailorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='retail.retailproduct')),
            ],
            options={
                'ordering': ['product_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='retail.retailorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='retail.retailproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('packaging_snapshot', models.CharField(blank=True, max_length=255)),
                ('sales_unit_snapshot', models.CharField(blank=True, max_length=120)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail.retailcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailproduct')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
