# Generated by Django 5.2.17 on 2026-08-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_invoice_labresult_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='access_conditions',
            field=models.TextField(blank=True, default='Sur Rendez-vous', null=True),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'Service Général'), ('SPECIALIZED', 'Service Spécialisé'), ('CARE_PACKAGE', 'Paquet de Soins')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='head_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_services', to='hospital.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='indicative_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='online_booking_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='operating_hours',
            field=models.CharField(blank=True, default='24h/24, 7j/7', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='telemedicine_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
