# Generated by Django 5.2.17 on 2026-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_medicalservice_access_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='assigned_doctors', to='hospital.medicalservice'),
        ),
    ]
