# Generated by Django 5.2.17 on 2026-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_doctorprofile_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='accepted_payment_methods',
            field=models.CharField(default='Espèces, Mobile Money, Carte Bancaire', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.IntegerField(default=5, help_text="Années d'expérience professionnelle"),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(default='Français, Kirundi', help_text='Langues parlées', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Photo professionnelle du médecin', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Qualifications et diplômes', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='sub_specialty',
            field=models.CharField(blank=True, help_text='Sous-spécialité (ex: Cardiologie Pédiatrique)', max_length=150, null=True),
        ),
    ]
