# Generated by Django 5.2.17 on 2026-08-20 14:25

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_businessrole_permissions'),
        ('hospital', '0008_auto_20260820_1423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('LAB_RESULT', 'Résultat de laboratoire'), ('APPOINTMENT_REMINDER', 'Rappel de rendez-vous'), ('PRESCRIPTION_READY', 'Prescription prête'), ('INVOICE_PAYMENT', 'Facture à payer'), ('GENERAL', 'Information générale')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_type', models.CharField(choices=[('MEDICATION', 'Médicament'), ('EXAM', 'Examen'), ('PROCEDURE', 'Procédure')], max_length=20)),
                ('medication_name', models.CharField(blank=True, help_text='Nom du médicament', max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='Dosage (ex: 500mg)', max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='Fréquence (ex: 3 fois par jour)', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='Durée (ex: 7 jours)', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Instructions spéciales')),
                ('exam_name', models.CharField(blank=True, help_text="Nom de l'examen", max_length=255)),
                ('exam_reason', models.TextField(blank=True, help_text="Raison de l'examen")),
                ('is_active', models.BooleanField(default=True)),
                ('is_dispensed', models.BooleanField(default=False, help_text='Médicament délivré')),
                ('is_completed', models.BooleanField(default=False, help_text='Examen complété')),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, help_text="Date de validité de l'ordonnance", null=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Profil Médecin', 'verbose_name_plural': 'Profils Médecins'},
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Résultat de laboratoire', 'verbose_name_plural': 'Résultats de laboratoire'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text="Motif d'annulation ou de reprogrammation", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text="Date d'annulation", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant annulé le rendez-vous', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date de clôture du rendez-vous', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Date de confirmation du rendez-vous', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location_notes',
            field=models.CharField(blank=True, help_text='Précisions sur le lieu (salle, étage, building…)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False, help_text='Rappel 1h avant envoyé'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False, help_text='Rappel 24h avant envoyé'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_to',
            field=models.ForeignKey(blank=True, help_text="Nouveau rendez-vous créé lors d'une reprogrammation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='hospital.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telemedicine_link',
            field=models.URLField(blank=True, help_text='Lien de la salle de téléconsultation (généré automatiquement)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telemedicine_room_id',
            field=models.CharField(blank=True, help_text='Identifiant de salle (Jitsi / Daily.co / autre)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee_currency',
            field=models.CharField(default='BIF', help_text='Devise du tarif (BIF, USD, EUR…)', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='diaspora_country',
            field=models.CharField(blank=True, help_text='Pays de résidence du médecin diaspora', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='diaspora_institution',
            field=models.CharField(blank=True, help_text="Établissement de rattachement à l'étranger", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='diaspora_timezone',
            field=models.CharField(blank=True, help_text='Fuseau horaire du médecin diaspora (ex: Europe/Paris, America/New_York)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='diaspora_verification_status',
            field=models.CharField(choices=[('PENDING', 'Candidature en attente'), ('UNDER_REVIEW', 'Documents en vérification'), ('VALIDATED', 'Validé'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu')], default='PENDING', help_text='Statut de vérification du médecin diaspora', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_accepting_new_patients',
            field=models.BooleanField(default=True, help_text='Le médecin accepte de nouveaux patients'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour masquer le médecin du répertoire sans supprimer son profil'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_available_for_tele_expertise',
            field=models.BooleanField(default=False, help_text="Le médecin peut fournir un avis de télé-expertise à d'autres médecins"),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_diaspora',
            field=models.BooleanField(default=False, help_text='Ce médecin fait partie du réseau des spécialistes à distance (diaspora)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_physical_consultation',
            field=models.BooleanField(default=True, help_text='Le médecin reçoit des patients en présentiel'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_title',
            field=models.CharField(choices=[('DR', 'Dr'), ('PR', 'Pr (Professeur)'), ('MG', 'Médecin Généraliste'), ('SPEC', 'Spécialiste'), ('SAGE_FEMME', 'Sage-femme'), ('INFIRMIER', 'Infirmier(e)'), ('PHARMACIEN', 'Pharmacien(ne)'), ('KINESITHERAPEUTE', 'Kinésithérapeute'), ('NUTRITIONNISTE', 'Nutritionniste'), ('PSYCHOLOGUE', 'Psychologue'), ('AUTRE', 'Autre professionnel de santé')], default='DR', help_text="Titre professionnel affiché dans l'annuaire", max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='tele_expertise_count',
            field=models.IntegerField(default=0, help_text='Nombre de télé-expertises réalisées sur la plateforme'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='communication_date',
            field=models.DateTimeField(blank=True, help_text='Date de communication au patient', null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='reference_values',
            field=models.TextField(blank=True, help_text='Valeurs de référence normales'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='result_value',
            field=models.CharField(default='N/A', help_text='Valeur du résultat', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Demandé'), ('SAMPLE_COLLECTED', 'Prélèvement effectué'), ('IN_ANALYSIS', 'En analyse'), ('RESULT_AVAILABLE', 'Résultat disponible'), ('VALIDATED', 'Validé'), ('COMMUNICATED', 'Communiqué')], default='REQUESTED', max_length=30),
        ),
        migrations.AddField(
            model_name='labresult',
            name='test_date',
            field=models.DateField(default=datetime.date(2026, 8, 20), help_text="Date de l'examen"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labresult',
            name='unit',
            field=models.CharField(blank=True, help_text='Unité de mesure', max_length=50),
        ),
        migrations.AddField(
            model_name='labresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_labs', to='hospital.doctorprofile'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='validation_date',
            field=models.DateTimeField(blank=True, help_text='Date de validation du résultat', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(help_text='Date et heure du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('IN_PERSON', 'En présentiel'), ('TELEMEDICINE', 'Téléconsultation'), ('TELE_EXPERTISE', 'Télé-expertise (entre médecins)')], default='IN_PERSON', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes cliniques post-consultation (remplies par le médecin)', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='Motif de la consultation', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('RESCHEDULED', 'Reprogrammé'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Patient absent')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='accepted_payment_methods',
            field=models.CharField(default='Espèces, Mobile Money, Carte Bancaire', help_text='Méthodes de paiement acceptées', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Biographie courte visible par le patient', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tarif de consultation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('NB', 'Non précisé')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hôpital ou clinique de rattachement principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_available_for_telemedicine',
            field=models.BooleanField(default=False, help_text='Le médecin est disponible pour des téléconsultations'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(default='Français, Kirundi', help_text='Langues parlées (séparées par des virgules)', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license_number',
            field=models.CharField(help_text="Numéro d'ordre professionnel (Ordre des Médecins du Burundi)", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL de la photo professionnelle du médecin', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Diplômes, formations et qualifications', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='accepted_insurances',
            field=models.JSONField(blank=True, default=list, help_text="Liste des compagnies d'assurance acceptées"),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='accreditation_body',
            field=models.CharField(blank=True, help_text="Organisme d'accréditation (ex: Ministère de la Santé du Burundi)", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='accreditation_number',
            field=models.CharField(blank=True, help_text="Numéro d'agrément ministériel ou d'accréditation", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='accreditation_valid_until',
            field=models.DateField(blank=True, help_text="Date d'expiration de l'agrément", null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='bed_capacity',
            field=models.IntegerField(blank=True, help_text='Nombre de lits disponibles', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='business',
            field=models.OneToOneField(help_text='Référence vers la fiche Business générique de cet hôpital', on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Image de couverture de la page hôpital', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='customer_service_available_24_7',
            field=models.BooleanField(default=False, help_text='Service clientèle disponible 24h/24, 7j/7'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='customer_service_email',
            field=models.EmailField(blank=True, help_text='Email dédié au service clientèle', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='customer_service_phone',
            field=models.CharField(blank=True, help_text='Numéro dédié au service clientèle', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='customer_service_whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp du service clientèle', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='emergency_available',
            field=models.BooleanField(default=False, help_text="Service d'urgences disponible 24h/24 — affiché sur la carte"),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Numéro direct des urgences (peut différer du numéro principal)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='gallery_urls',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'URLs des photos de l'établissement"),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital_type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Privé'), ('FAITH_BASED', 'Confessionnel'), ('NGO', 'ONG / Humanitaire'), ('MILITARY', 'Militaire'), ('OTHER', 'Autre')], default='PRIVATE', help_text="Type d'établissement (public, privé, confessionnel…)", max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='icu_beds',
            field=models.IntegerField(blank=True, help_text='Nombre de lits en soins intensifs (USI)', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='languages_available',
            field=models.CharField(default='Français, Kirundi', help_text='Langues parlées par le personnel (séparées par des virgules)', max_length=300),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='level',
            field=models.CharField(choices=[('HEALTH_POST', 'Poste de santé'), ('HEALTH_CENTER', 'Centre de santé'), ('DISTRICT_HOSPITAL', 'Hôpital de district'), ('PROVINCIAL_HOSPITAL', 'Hôpital provincial'), ('NATIONAL_HOSPITAL', 'Hôpital national'), ('SPECIALIZED_HOSPITAL', 'Hôpital spécialisé'), ('CLINIC', 'Clinique privée'), ('POLYCLINIC', 'Polyclinique')], default='CLINIC', help_text="Niveau de l'établissement dans la pyramide sanitaire", max_length=30),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Horaires par jour de la semaine (JSON structuré)'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='operational_status',
            field=models.CharField(choices=[('ACTIVE', 'En activité'), ('TEMPORARILY_CLOSED', 'Temporairement fermé'), ('UNDER_RENOVATION', 'En rénovation'), ('CLOSED', 'Fermé définitivement')], default='ACTIVE', help_text="Statut opérationnel actuel de l'établissement", max_length=30),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='presentation_video_url',
            field=models.URLField(blank=True, help_text='URL de la vidéo de présentation (YouTube, Vimeo…)', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='reference_level',
            field=models.CharField(blank=True, choices=[('LEVEL_1', 'Niveau 1 — Soins primaires'), ('LEVEL_2', 'Niveau 2 — Soins secondaires'), ('LEVEL_3', 'Niveau 3 — Soins tertiaires / Spécialisés'), ('LEVEL_4', 'Niveau 4 — Soins quaternaires / Super-spécialisés')], help_text='Niveau auquel cet établissement peut recevoir les références', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='telemedicine_unit_available',
            field=models.BooleanField(default=False, help_text="L'hôpital dispose d'une unité physique de télémédecine"),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='telemedicine_unit_description',
            field=models.TextField(blank=True, help_text="Description de l'espace télémédecine (équipements, localisation…)", null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result_notes',
            field=models.TextField(blank=True, help_text='Commentaires sur le résultat'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=models.CharField(help_text="Nom de l'examen", max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='access_conditions',
            field=models.TextField(blank=True, default='Sur Rendez-vous', help_text="Conditions d'accès au service (prescription requise, référencement, etc.)", null=True),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='availability',
            field=models.CharField(choices=[('H24_7', '24h/24 — 7j/7'), ('BUSINESS_HOURS', 'Heures ouvrables uniquement'), ('BY_APPOINTMENT', 'Sur rendez-vous'), ('MORNING_ONLY', 'Matin uniquement'), ('AFTERNOON_ONLY', 'Après-midi uniquement'), ('SPECIFIC_DAYS', 'Jours spécifiques (voir horaires)'), ('TEMPORARILY_UNAVAILABLE', 'Temporairement indisponible')], default='BY_APPOINTMENT', help_text='Disponibilité générale du service', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'Service Général'), ('SPECIALIZED', 'Service Spécialisé'), ('CARE_PACKAGE', 'Paquet de Soins'), ('DIAGNOSTIC', 'Diagnostic & Imagerie'), ('SURGICAL', 'Chirurgie'), ('EMERGENCY', 'Urgences'), ('MATERNITY', 'Maternité & Obstétrique'), ('PEDIATRIC', 'Pédiatrie'), ('REHABILITATION', 'Rééducation & Kinésithérapie'), ('PHARMACY', 'Pharmacie'), ('TELEMEDICINE', 'Télémédecine')], default='GENERAL', help_text='Catégorie principale du service', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email direct du service', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Numéro de contact direct du service (peut différer du numéro principal)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='cost_notes',
            field=models.CharField(blank=True, help_text="Note sur le tarif (ex: 'Tarif réduit pour les assurés INSS')", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='currency',
            field=models.CharField(default='BIF', help_text='Devise utilisée pour le tarif (BIF, USD, EUR…)', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='description',
            field=models.TextField(blank=True, help_text="Description détaillée du service et de ce qu'il couvre", null=True),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='display_order',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)"),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='head_doctor',
            field=models.ForeignKey(blank=True, help_text='Médecin responsable du service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_services', to='hospital.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='hospital',
            field=models.ForeignKey(help_text='Hôpital ou établissement proposant ce service', on_delete=django.db.models.deletion.CASCADE, related_name='medical_services', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='indicative_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Coût indicatif en BIF (0 = gratuit ou à définir)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour masquer ce service sans le supprimer'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='name',
            field=models.CharField(help_text="Nom du service tel qu'affiché au patient", max_length=150),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='online_booking_available',
            field=models.BooleanField(default=True, help_text='La prise de rendez-vous en ligne est disponible pour ce service'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Horaires détaillés par jour. Ex: {"lundi": {"open": "08:00", "close": "17:00"}}'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='service_type',
            field=models.CharField(choices=[('INTERNAL_MEDICINE', 'Médecine interne'), ('GENERAL_SURGERY', 'Chirurgie générale'), ('PEDIATRICS', 'Pédiatrie'), ('OBSTETRICS_GYNECOLOGY', 'Gynécologie-Obstétrique'), ('EMERGENCY', 'Urgences'), ('MATERNITY', 'Maternité'), ('DENTISTRY', 'Dentisterie'), ('CARDIOLOGY', 'Cardiologie'), ('NEUROLOGY', 'Neurologie'), ('NEPHROLOGY', 'Néphrologie'), ('ONCOLOGY', 'Oncologie'), ('ORTHOPEDICS', 'Orthopédie'), ('OPHTHALMOLOGY', 'Ophtalmologie'), ('DERMATOLOGY', 'Dermatologie'), ('PSYCHIATRY', 'Psychiatrie'), ('PULMONOLOGY', 'Pneumologie'), ('GASTROENTEROLOGY', 'Gastroentérologie'), ('ENDOCRINOLOGY', 'Endocrinologie'), ('RHEUMATOLOGY', 'Rhumatologie'), ('UROLOGY', 'Urologie'), ('ENT', 'ORL (Oto-rhino-laryngologie)'), ('HEMATOLOGY', 'Hématologie'), ('INFECTIOUS_DISEASE', 'Maladies infectieuses'), ('RADIOLOGY', 'Radiologie'), ('ECHOGRAPHY', 'Échographie'), ('SCANNER_MRI', 'Scanner / IRM'), ('LABORATORY', 'Analyses de laboratoire'), ('CARDIAC_SURGERY', 'Chirurgie cardiaque'), ('NEUROSURGERY', 'Neurochirurgie'), ('PLASTIC_SURGERY', 'Chirurgie plastique'), ('VASCULAR_SURGERY', 'Chirurgie vasculaire'), ('PHYSIOTHERAPY', 'Kinésithérapie'), ('NUTRITION', 'Nutrition & Diététique'), ('PSYCHOLOGY', 'Psychologie'), ('PALLIATIVE_CARE', 'Soins palliatifs'), ('BLOOD_BANK', 'Banque de sang'), ('VACCINATION', 'Vaccination & Prévention'), ('OTHER', 'Autre')], default='OTHER', help_text='Type précis du service (utilisé pour les filtres et la recherche)', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='telemedicine_available',
            field=models.BooleanField(default=False, help_text='Ce service peut être consulté à distance via télémédecine'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='idx_appt_patient_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='idx_appt_doctor_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'status'], name='idx_appt_hospital_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'reminder_24h_sent'], name='idx_appt_reminder_24h'),
        ),
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hospital.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lab_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hospital.labresult'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.doctorprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
