# Generated by Django 5.2.17 on 2026-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_notification_prescription_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='staff_category',
            field=models.CharField(choices=[('SPECIALIST', 'Médecin Spécialiste'), ('DOCTOR', 'Docteur / Généraliste'), ('NURSE', 'Infirmier(e) / Soignant(e)')], default='DOCTOR', help_text='Catégorie du personnel : Médecin Spécialiste, Docteur/Généraliste, ou Infirmier(e)', max_length=20),
        ),
    ]
