# Generated by Django 5.2.17 on 2026-08-28 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_businessrole_permissions'),
        ('hospital', '0010_doctorprofile_staff_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, help_text="Numéro d'ordre du patient selon l'ordre de postulation", null=True),
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Consultation Médicale', help_text='Intitulé de la session (ex: Consultation Cardiologie)', max_length=200)),
                ('slot_date', models.DateField(help_text='Date de la session')),
                ('start_time', models.TimeField(help_text='Heure de début')),
                ('end_time', models.TimeField(help_text='Heure de fin')),
                ('consultation_type', models.CharField(choices=[('IN_PERSON', 'En présentiel'), ('TELEMEDICINE', 'Téléconsultation'), ('TELE_EXPERTISE', 'Télé-expertise')], default='IN_PERSON', max_length=20)),
                ('max_patients', models.PositiveIntegerField(default=10, help_text='Nombre maximum de personnes acceptées pour cette session')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert aux réservations'), ('FULL', 'Complet'), ('CANCELLED', 'Annulé'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='hospital.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='businesses.business')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_slots', to='hospital.medicalservice')),
            ],
            options={
                'verbose_name': 'Créneau de Rendez-vous',
                'verbose_name_plural': 'Créneaux de Rendez-vous',
                'ordering': ['slot_date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, help_text="Session / créneau de rendez-vous défini par l'administration", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital.appointmentslot'),
        ),
    ]
