# Generated by Django 5.2.17 on 2026-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_appointment_queue_number_appointmentslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Permet à l'admin d'activer/désactiver la visibilité du rendez-vous côté patient"),
        ),
    ]
