# Generated by Django 5.2.17 on 2026-08-28 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_businessrole_permissions'),
        ('hospital', '0012_appointmentslot_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_service', models.CharField(choices=[('HEAD', 'Chef de service / Responsable'), ('PRACTITIONER', 'Praticien / Intervenant principal'), ('ASSISTANT', 'Assistant / Soignant'), ('STAFF', 'Personnel de support / Administratif')], default='PRACTITIONER', max_length=30)),
                ('is_primary', models.BooleanField(default=True, help_text="Est le service principal de l'utilisateur")),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='businesses.business')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospital.medicalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation de Service',
                'verbose_name_plural': 'Affectations de Services',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'service')},
            },
        ),
    ]
