# Generated by Django 5.2.17 on 2026-08-28 14:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_businessrole_permissions'),
        ('hospital', '0013_serviceassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Catégorie de Prestation',
                'verbose_name_plural': 'Catégories de Prestation',
                'ordering': ['name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
    ]
