# Generated by Django 5.2.17 on 2026-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_remove_confirmation_default_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Numéro de suivi patient (ex: RDV-2026-00042)', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='photo_url',
            field=models.TextField(blank=True, help_text='URL ou image Base64 de la photo professionnelle (publique)', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='staff_category',
            field=models.CharField(choices=[('SPECIALIST', 'Médecin Spécialiste'), ('DOCTOR', 'Docteur / Généraliste'), ('NURSE', 'Infirmier(e) / Soignant(e)'), ('RECEPTIONIST', "Agent d'accueil")], default='DOCTOR', help_text='Catégorie du personnel : Médecin Spécialiste, Docteur/Généraliste, ou Infirmier(e)', max_length=20),
        ),
    ]
