# Generated by Django 5.2.17 on 2026-09-08 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_alter_businessrole_system_access_level'),
        ('hospital', '0024_doctor_photo_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nom de l'examen affiché au patient", max_length=200)),
                ('category', models.CharField(choices=[('LABORATORY', 'Laboratoire / Analyses'), ('IMAGING', 'Imagerie (Radio, Echo, Scanner…)'), ('CARDIOLOGY', 'Examens cardiologiques'), ('OTHER', 'Autre examen')], default='LABORATORY', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description courte pour le patient')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text="Tarif de l'examen", max_digits=12)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('price_notes', models.CharField(blank=True, help_text='Ex: Tarif assuré INSS, préparation à jeun…', max_length=300)),
                ('preparation', models.TextField(blank=True, help_text='Consignes de préparation (à jeun, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text="Afficher cet examen sur la fiche publique de l'hôpital")),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(help_text='Hôpital proposant cet examen', on_delete=django.db.models.deletion.CASCADE, related_name='hospital_exams', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Examen hospitalier',
                'verbose_name_plural': 'Examens hospitaliers',
                'ordering': ['display_order', 'category', 'name'],
                'indexes': [models.Index(fields=['hospital', 'is_active', 'is_public'], name='idx_exam_hospital_public')],
            },
        ),
    ]
