# Generated by Django 5.2.17 on 2026-08-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='business_categories.businesscategory'),
        ),
    ]
